<?php

namespace whatwedo\CronBundle\Tests\App\CronJob;

use whatwedo\CronBundle\CronJob\AbstractCronJob;

class DemoCron extends AbstractCronJob
{
    public function getDescription(): ?string
    {
        return 'Is only a test Cron Job';
    }

    public function getArguments(): array
    {
        return parent::getArguments(); // TODO: Change the autogenerated stub
    }

    public function getCommand(): string
    {
        return 'list';
    }

    public function getExpression(): string
    {
        return '*/5 * * * * ';
    }
}